#!/usr/bin/env bash
# =============================================================================
# run_demo.sh — MissionForge End-to-End Demo Script
#
# Starts the full stack with Docker Compose and runs a fault injection
# demonstration that proves the semantic overlay capability.
#
# Usage:
#   chmod +x demo/run_demo.sh
#   ./demo/run_demo.sh
# =============================================================================

set -euo pipefail

ADAPTER_URL="http://localhost:8000"
DASHBOARD_URL="http://localhost:8080"

# Colours
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

banner() {
  echo -e "${CYAN}${BOLD}"
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║         MissionForge — Demo Script                  ║"
  echo "  ║  Computational Upcycling of Legacy CORBA Systems    ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo -e "${NC}"
}

step() { echo -e "\n${GREEN}▶ $1${NC}"; }
info() { echo -e "  ${CYAN}$1${NC}"; }
warn() { echo -e "  ${YELLOW}$1${NC}"; }

# Change to repo root (parent of demo/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

banner

# ---------------------------------------------------------------------------
# Step 1: Build and start services
# ---------------------------------------------------------------------------
step "Building and starting MissionForge with Docker Compose…"
docker compose up --build -d

# ---------------------------------------------------------------------------
# Step 2: Wait for adapter to be ready
# ---------------------------------------------------------------------------
step "Waiting for MissionForge adapter to be ready…"
for i in $(seq 1 30); do
  if curl -sf "$ADAPTER_URL/" >/dev/null 2>&1; then
    echo -e "  ${GREEN}✓ Adapter ready (${i}s)${NC}"
    break
  fi
  echo -n "."
  sleep 1
  if [ "$i" -eq 30 ]; then
    warn "Adapter did not respond after 30s — check: docker compose logs"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Step 3: Wait for first telemetry
# ---------------------------------------------------------------------------
step "Waiting for first telemetry from legacy CORBA server…"
for i in $(seq 1 20); do
  if curl -sf "$ADAPTER_URL/telemetry/latest" >/dev/null 2>&1; then
    echo -e "  ${GREEN}✓ Telemetry received${NC}"
    break
  fi
  echo -n "."
  sleep 1
  if [ "$i" -eq 20 ]; then
    warn "No telemetry after 20s — the CORBA bridge may still be starting"
  fi
done

# ---------------------------------------------------------------------------
# Step 4: Show initial state
# ---------------------------------------------------------------------------
step "Baseline telemetry (legacy CORBA app — normal operation):"
curl -sf "$ADAPTER_URL/telemetry/latest" | python3 -m json.tool || true

echo ""
step "Baseline health score:"
curl -sf "$ADAPTER_URL/health" | python3 -m json.tool || true

# ---------------------------------------------------------------------------
# Step 5: Inject fault
# ---------------------------------------------------------------------------
step "Injecting fault — simulating legacy system degradation…"
info "This demonstrates the MissionForge semantic overlay detecting a"
info "failure WITHOUT modifying the legacy CORBA application."
echo ""
curl -sf -X POST "$ADAPTER_URL/demo/inject-fault" \
     -H "Content-Type: application/json" \
     -d '{}' | python3 -m json.tool || true

# ---------------------------------------------------------------------------
# Step 6: Watch for alerts
# ---------------------------------------------------------------------------
step "Monitoring alerts for 20 seconds…"
for i in $(seq 1 20); do
  sleep 1
  ALERTS=$(curl -sf "$ADAPTER_URL/alerts?limit=5" 2>/dev/null || echo "[]")
  HEALTH=$(curl -sf "$ADAPTER_URL/health" 2>/dev/null || echo '{"score":0,"status":"?"}')
  SCORE=$(echo "$HEALTH" | python3 -c "import sys,json; d=json.load(sys.stdin); print(f\"{d['score']:.0f}\")" 2>/dev/null || echo "?")
  STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['status'])" 2>/dev/null || echo "?")
  NALERTS=$(echo "$ALERTS" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")
  echo -e "  t+${i}s  Health: ${BOLD}${SCORE}/100${NC} [${STATUS}]  Alerts: ${NALERTS}"
done

# ---------------------------------------------------------------------------
# Step 7: Show final state
# ---------------------------------------------------------------------------
step "Final alerts (generated by MissionForge semantic overlay):"
curl -sf "$ADAPTER_URL/alerts?limit=10" | python3 -m json.tool || true

step "Final health score:"
curl -sf "$ADAPTER_URL/health" | python3 -m json.tool || true

# ---------------------------------------------------------------------------
# Step 8: Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}${GREEN}Demo complete!${NC}"
echo ""
info "What just happened:"
info "  1. Legacy CORBA telemetry server ran UNCHANGED"
info "  2. MissionForge observed telemetry EXTERNALLY"
info "  3. Semantic overlay detected degradation and raised alerts"
info "  4. No legacy hardware or software was modified"
echo ""
info "Dashboard: $DASHBOARD_URL"
info "API docs:  $ADAPTER_URL/docs"
echo ""
info "To reset:  curl -X POST $ADAPTER_URL/demo/reset"
info "To stop:   docker compose down"
