"""
schemas.py — Pydantic models for the MissionForge adapter.

These schemas define the data contracts between:
  - the CORBA bridge (inbound telemetry)
  - the FastAPI endpoints (outbound telemetry, health, alerts)
"""

from __future__ import annotations
from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class TelemetryReading(BaseModel):
    """A single telemetry snapshot from the legacy mission computer."""
    engine_temp: float = Field(..., description="Engine temperature (°C)")
    vibration: float = Field(..., description="Vibration level (g)")
    fuel_flow: float = Field(..., description="Fuel flow rate (kg/min)")
    oil_pressure: float = Field(..., description="Oil pressure (PSI)")
    cpu_usage: float = Field(..., description="CPU utilization (%)")
    memory_usage: float = Field(..., description="Memory utilization (%)")
    sensor_status: str = Field(..., description="Sensor health: OK | DEGRADED | FAILED")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp")

    class Config:
        json_schema_extra = {
            "example": {
                "engine_temp": 185.2,
                "vibration": 0.24,
                "fuel_flow": 82.1,
                "oil_pressure": 44.0,
                "cpu_usage": 38.2,
                "memory_usage": 61.0,
                "sensor_status": "OK",
                "timestamp": "2026-06-05T12:00:00Z",
            }
        }


class Alert(BaseModel):
    """A predictive maintenance or anomaly alert generated by the semantic overlay."""
    alert_type: str = Field(..., description="Alert category identifier")
    severity: str = Field(..., description="LOW | MEDIUM | HIGH | CRITICAL")
    explanation: str = Field(..., description="Human-readable description")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp when alert was raised")
    contributing_signals: List[str] = Field(
        default_factory=list,
        description="Telemetry fields that contributed to this alert",
    )


class HealthStatus(BaseModel):
    """Overall system health report."""
    score: float = Field(..., ge=0, le=100, description="Health score 0–100")
    status: str = Field(..., description="NOMINAL | DEGRADED | CRITICAL")
    active_alert_count: int
    last_updated: str
    details: dict = Field(default_factory=dict)


class FaultInjectionRequest(BaseModel):
    """Parameters for demo fault injection."""
    fault_type: str = Field(
        default="engine_overheat",
        description="Fault scenario: engine_overheat | vibration_spike | pressure_drop | combined",
    )


class SystemStatus(BaseModel):
    """Top-level status response."""
    running: bool = True
    mode: str = "mock"  # "mock" or "tao"
    telemetry_count: int = 0
    uptime_seconds: float = 0.0
    fault_active: bool = False
